name: Enrichment
language: python
variables:
  - name: data_topic
    inputType: InputTopic
    multiline: false
    description: This is the input topic for f1 data
    defaultValue: solar-farm
    required: true
  - name: output
    inputType: OutputTopic
    multiline: false
    description: This is the output topic for hard braking events
    defaultValue: enriched_data
    required: true
  - name: config_topic
    inputType: InputTopic
    multiline: false
    defaultValue: configuration
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
libraryItemId: event-detection-transformation
